### ISSUE TITLE
Categories aren't shown in Visual Studio when MTP is on

### ISSUE THREAD

**Issue by victorburckel** [nunit/nunit3-vs-adapter#1258]
Hi,

Don't know if this is a nunit adapter issue, but I tried switching to Microsoft Testing Platform, and categories don't show up in the editor anymore:

![Image](https://github.com/user-attachments/assets/5e39052a-fd0f-497b-b5bb-aaf93ddd0b56)

Is this an issue with the adapter ? 

Here is my simple test code:
```cs
namespace NUnitMTP
{
    public class Tests
    {
        [Test, Category("Cat1")]
        public void Test1()
        {
            Assert.Pass();
        }

        [Test, Category("Cat2")]
        public void Test2()
        {
            Assert.Pass();
        }
    }
}
```

and my csproj is as follows:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    
    <EnableNUnitRunner>true</EnableNUnitRunner>
    <OutputType>Exe</OutputType>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
    <PackageReference Include="NUnit" Version="4.3.2" />
    <PackageReference Include="NUnit.Analyzers" Version="4.6.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NUnit3TestAdapter" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework" />
  </ItemGroup>

</Project>
```

**Comment by OsirisTerje** [comment]
I can confirm this.
I also checked what we get back from the framework, and it does include the categories:

<img width="1046" alt="Image" src="https://github.com/user-attachments/assets/e19c9dd4-370d-4203-ad2d-eda5443a9a64" />

I have uploaded the repro here: https://github.com/nunit/nunit3-vs-adapter.issues/tree/master/Issue1258

@Evangelink I didn't think the MTP did any changes to the processing of the categories, that should be entirely on the adapter side. Do you understand what is going on here ?

**Comment by OsirisTerje** [comment]
According to @Youssef1313 this is a VSTestBridge issue, and a fix is under way here:  https://github.com/microsoft/testfx/pull/5409

**Comment by Youssef1313** [comment]
Looking again, this might have been also fixed by https://github.com/microsoft/testfx/pull/5316

**Comment by victorburckel** [comment]
Not sure I did the test correctly, but I tried to force `<PackageReference Include="Microsoft.Testing.Extensions.VSTestBridge" Version="1.7.0" />` in the previous dummy project to switch to the latest release, but it seems like I still get the issue.

**Comment by OsirisTerje** [comment]
@nohwnd Just checked this with the latest alpha.3 which includes the 1.7.0 bridge, and no change - still no categories showing in TE.

**Comment by Youssef1313** [comment]
@OsirisTerje We can handle it on our side. I'm doing it in https://github.com/microsoft/testfx/pull/5644.
