### ISSUE TITLE
Incompatibility with MTP mode in .NET 10 SDK

### ISSUE THREAD

**Issue by philipp-naused** [nunit/nunit3-vs-adapter#1267]
.NET 10 has a new opt-in MPT mode that changes the behavior of `dotnet test`.
See: <https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-dotnet-test#microsofttestingplatform-mtp-mode-of-dotnet-test>

NUnit3TestAdapter doesn't seem to work in this new mode.

Repo steps:
1. Create a Nuit project that uses MTP:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableNUnitRunner>true</EnableNUnitRunner>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
    <PackageReference Include="NUnit" Version="4.3.2" />
    <PackageReference Include="NUnit3TestAdapter" Version="5.0.0" />
  </ItemGroup>
</Project>
```
2. Create a `dotnet.config` file at the root of the repo to enable MTP mode:
```ini
[dotnet.test:runner]
name = "Microsoft.Testing.Platform"
```
3. Run `dotnet test` using .NET 10 SDK (10.0.100-preview.3.25201.16)

Result:
```
When opting-in via dotnet.config, all test projects are expected to be using Microsoft.Testing.Platform.
The following test projects are using VSTest:
Test1.csproj
See https://aka.ms/dotnet-test/mtp for more information.

Test run summary: Zero tests ran
  total: 0
  failed: 0
  succeeded: 0
  skipped: 0
  duration: 1s 282ms
```

According to MS docs, this error should occur when a test project supports VSTest, but not MTP.
This may also be an issue with the .NET SDK not recognizing NUnit as supporting MTP.

MSTest is correctly recognized:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableMSTestRunner>true</EnableMSTestRunner>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
    <PackageReference Include="MSTest" Version="3.8.3" />
  </ItemGroup>
</Project>
```

**Comment by OsirisTerje** [comment]
@Evangelink @Youssef1313  Can you comment ?

**Comment by philipp-naused** [comment]
I added `<IsTestingPlatformApplication>true</IsTestingPlatformApplication>` to the project, and now it is working!
So #1262 will likely fix this.

**Comment by Evangelink** [comment]
@OsirisTerje I think the PR linked by @philipp-naused is most likely the cause/fix.

**Comment by Youssef1313** [comment]
Yes, that PR should fix it, hopefully.

**Comment by philipp-naused** [comment]
Ok, it works now in MPT 1.7.0.

**Comment by philipp-naused** [comment]
But it only works if I manually add:
```xml
<PackageReference Include="Microsoft.Testing.Platform" Version="1.7.0" />
<PackageReference Include="Microsoft.Testing.Extensions.VSTestBridge" Version="1.7.0" />
```
The real fix will be to update NUnit3TestAdapter's dependencies to the MTP packages.

**Comment by philipp-naused** [comment]
Oops, I mixed this up with https://github.com/dotnet/sdk/issues/48912.

This issue isn't fixed yet.

**Comment by OsirisTerje** [comment]
@philipp-naused Just released https://www.nuget.org/packages/NUnit3TestAdapter/5.1.0-alpha.2 .  Can you check ?

**Comment by philipp-naused** [comment]
@OsirisTerje, @Youssef1313 Yes, it's working with 5.1.0-alpha.2 and .NET 10 Preview 4.

**Comment by moh-hassan** [comment]
I face the same issue in net10 preview7. I use  NUnit3TestAdapter v 5.0.0
 I add `dotnet.config` in the solution folder as [described](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-test?tabs=dotnet-test-with-mtp) in docs:
```
[dotnet.test.runner]
name = "Microsoft.Testing.Platform"
```
i can run test from vs2022 Test explorer without problem.
when run `dotnet test` , i get the error:
>dotnet.config defines test runner to be Microsoft.Testing.Platform. All projects must use that test runner.
The following test projects are using VSTest test runner:
nunit-runner-dotnet-test-net10.csproj

I tried to use v 5.1.0-alpha.2 , and it's working. 
BUT it seem it is working as `VSTest` mode because there is no log folder indicate it is working as MTP.

If i remove the file `dotnet.config` , it works as MTP and log is generated.

**Comment by Youssef1313** [comment]
If you have a repro for that, please open an issue in dotnet/sdk and tag me there
