### ISSUE TITLE
I am getting a System.InvalidCastException when updating from NUnit3TestAdapter Version=5.2.0 to 6.0.1

### ISSUE THREAD

**Issue by Sveti86** [nunit/nunit3-vs-adapter#1390]
ThenGlobalReturnValueShouldBe_1
   Source: ScriptExecutorTests.cs line 61
   Duration: 351 ms

  Message: 
SetUp : System.InvalidCastException : [A]Globals cannot be cast to [B]Globals. Type A originates from 'zOS.DM.Server.Tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' in the context '"C:\Users\SvetoslavInkolov\source\repos\zDM\source\server\zOS.DM.Server.Tests\bin\Debug\net10.0\zOS.DM.Server.Tests.dll" System.Runtime.Loader.AssemblyLoadContext #2' at location 'C:\Users\SvetoslavInkolov\source\repos\zDM\source\server\zOS.DM.Server.Tests\bin\Debug\net10.0\zOS.DM.Server.Tests.dll'. Type B originates from 'zOS.DM.Server.Tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' in the context 'Default' at location 'C:\Users\SvetoslavInkolov\source\repos\zDM\source\server\zOS.DM.Server.Tests\bin\Debug\net10.0\zOS.DM.Server.Tests.dll'.

  Stack Trace: 
--SetUp
Submission#0.ctor(Object[] submissionArray)
Submission#0.<Factory>(Object[] submissionArray)
ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
Script`1.RunSubmissionsAsync(ScriptExecutionState executionState, ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
ScriptExecutor.ExecuteScriptAsync(String code, Object globals, Type globalsType, ScriptOptions scriptOptions) line 207
ScriptExecutor.ExecuteAsync(String code, Object globals, Type globalsType, ScriptOptions scriptOptions) line 108
ScriptExecutor.ExecuteAsync[TGlobals](String code, TGlobals globals) line 91
ScriptExecutorTestBase.When() line 44
GivenWhenTestBase.Setup() line 25
SetUpTearDownItem.RunSetUp(TestExecutionContext context)
1) --SetUp
Submission#0.ctor(Object[] submissionArray)
Submission#0.<Factory>(Object[] submissionArray)
ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
Script`1.RunSubmissionsAsync(ScriptExecutionState executionState, ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
ScriptExecutor.ExecuteScriptAsync(String code, Object globals, Type globalsType, ScriptOptions scriptOptions) line 207
ScriptExecutor.ExecuteAsync(String code, Object globals, Type globalsType, ScriptOptions scriptOptions) line 108
ScriptExecutor.ExecuteAsync[TGlobals](String code, TGlobals globals) line 91
ScriptExecutorTestBase.When() line 44
GivenWhenTestBase.Setup() line 25
SetUpTearDownItem.RunSetUp(TestExecutionContext context)

The test is here:

    public class WhenExecutingBlockStatementRegexOnArgumentVariable : ScriptExecutorTestBase
    {
        protected override void Given(IServiceCollection services)
        {
            _globals.StringArgument = "foo-bar";

            _script = @"
if (System.Text.RegularExpressions.Regex.IsMatch(StringArgument, ""\\w+\\w+""))
    ReturnValue = 1;
";
        }

        [Test]
        public void ThenGlobalReturnValueShouldBe_1()
        {
            Assert.That(_scriptResult, Is.True);
            Assert.That(_globals.ReturnValue, Is.EqualTo(1));
        }
    }

and the same Exception for this one:

    public class WhenExecutingSingleStatementRegexOnArgumentVariable : ScriptExecutorTestBase
    {
        protected override void Given(IServiceCollection services)
        {
            _globals.StringArgument = "foo-bar";

            _script = @"System.Text.RegularExpressions.Regex.IsMatch(StringArgument, ""\\w+\\w+"")";
        }

        protected override async Task When()
        {
            _scriptResult = await _scriptExecutor.ExecuteSingleStatementAsync(_script, _globals);
        }

        [Test]
        public void ThenReturnValueShouldBe_True()
        {
            Assert.That(_scriptResult, Is.True);
        }
    }

**Comment by OsirisTerje** [comment]
Thanks @Sveti86 .  This is another of the loading issues we do have with 6.X.  Take a  look at #1375 , you will see 3 of 4 mechanisms now work in 6.0.1.  You're probably hitting the 4th. 

We're working on getting the last one fixed in 6.1, but we need to update the engine to V4 and get rid of the double loading, which is what you see. 

Also see #1389 for a good explanation..

**Comment by Sveti86** [comment]
Okay thanks for fast reply, I will revert to version 5.2.0 for the time being and wait for the fix!

**Comment by OsirisTerje** [comment]
@Sveti86 Can you try 6.0.2-beta.1 .

**Comment by nesc58** [comment]
For me, the problem is not solved using the 6.0.2-beta.1:
Original code is something like
```csharp
AppDomain.CurrentDomain.GetAssemblies()
.Where(type => type.IsSubclassOf(MyType)))
.Where(type => !string.IsNullOrWhiteSpace(type.FullName))
.ToDictionary(type => type.FullName!, type => type, StringComparer.Ordinal)
```
which currently throws because the key already added. Grouping does not solve the problem because the context / assembly issues. 

When using the AssemblyLoadContext:
```csharp
(System.Runtime.Loader.AssemblyLoadContext.GetLoadContext(Assembly.GetExecutingAssembly())?.Assemblies.ToArray() ?? [])
.Where(type => type.IsSubclassOf(MyType)))
.Where(type => !string.IsNullOrWhiteSpace(type.FullName))
.ToDictionary(type => type.FullName!, type => type, StringComparer.Ordinal)
```

does not throws when creating the dictionary but later:
[A] cannot be cast to [B] Type A originates from in the context Default. Type B originates from in the Context '....Tests'

Using the default context `System.Runtime.Loader.AssemblyLoadContext.Default.Assemblies`  also throws.

Seems that its still double loading things. Maybe the project structure is the issue but 6.0.0 with net10.0 works fine.

Project structure:
ProjectA with the code for the assembly / ToDictionary stuff. Also contains MyType
ProjectB reference to ProjectA, contains classes which inherit MyType
ProjectC reference to B and calls the functions of ProjectA and some types also inherit MyType

**Comment by OsirisTerje** [comment]
@nesc58 Can you provide a small repro for this?   

I assume you're doing non-MTP here ?

Version 6.0.0 DO load twice if MTP, but only once with non-MTP - BUT it then loads into its own context, named like the name of the assembly.  
Version 6.0.2-beta.1 should load everything into the default AssemblyLoadContext.  

You can test this using the runsettings element UseDefaultAssemblyLoadContext  (bool).

**Comment by OsirisTerje** [comment]
@nesc58 Can you provide a small repro for this?   

I assume you're doing non-MTP here ?

Version 6.0.0 DO load twice if MTP, but only once with non-MTP - BUT it then loads into its own context, named like the name of the assembly.  
Version 6.0.2-beta.1 should load everything into the default AssemblyLoadContext.  

You can test this using the runsettings element UseDefaultAssemblyLoadContext  (bool). 

Also, does this match THIS particular issue - you get an InvalidCastException matching the stack trace above?   If not, can you please raise another issue for your particular case?

**Comment by nesc58** [comment]
@OsirisTerje  here is a small repro without changes: https://github.com/nesc58/NU1390

**Comment by OsirisTerje** [comment]
@nesc58 The repro works here.

<img width="1238" height="546" alt="Image" src="https://github.com/user-attachments/assets/69cd420a-be32-45ce-aa25-0d6cfecfe0ee" />

**Comment by nesc58** [comment]
Oh, for sure. After updating to the beta i have not tested the cli again.
It seems to be an Rider IDE issue

**Comment by OsirisTerje** [comment]
If you're using Rider only, then you don't need the NUnit3TestAdapter.

**Comment by nesc58** [comment]
I am using rider locally for testing and debugging. The CI/CD uses dotnet test.

**Comment by OsirisTerje** [comment]
Rider/Resharper will use the adapter's embedded engine if that is present - and that version is now 3.22.0.  The engine has a change in the way it loads assemblies, so when using the adapter we have to set a parameter UseDefaultAssemblyLoadContext.  Rider/Resharper needs to set this parameter too in order to make their test runner work alongside version 6 of the adapter.  
When the adapter is not present, Rider/resharper falls back to using NUnit.Engine 3.15.5, which use the default assembly loading context.  
Also, your code is MTP based, so you need to enable the Testing Platform support in Rider - although they have not yet implemented the support there - it is simply too early.

@estrizhok:  Should we raise a ticket or can you handle it ?

PS:  @nesc:  This is still different from this current issue. 

PS2:  You can work around this by 1) Let the action CI/CD script add in the adapter  2) Stay on 5.2.0 until this Rider is fixed.

**Comment by OsirisTerje** [comment]
@Sveti86 Can you confirm it works for you now ?

**Comment by Sveti86** [comment]
> [@Sveti86](https://github.com/Sveti86) Can you confirm it works for you now ?

Yes, I confirm that Version 6.0.2-beta.1 solves my issue too.
