### ISSUE TITLE
Profile Test in VS Runner throws

### ISSUE THREAD

**Issue by Dispersia** [nunit/nunit3-vs-adapter#371]
Using Visual Studio 2017 Enterprise, NUnit v3.7.1, NUnit3TestAdapter: v3.8, but was witnessed in last version as well.

 I haven't seen any documentation on the "Profile Test" option when right clicking a test in Test Explorer, when trying to run it, I receive the error:

> Error: Unable to get runner for this assembly. Check installation, including any extensions.
> NUnitEngineException: Cannot run tests in process - a 32 bit process is required.
> An exception occurred while invoking executor 'executor://nunit3testexecutor/': Cannot run tests in process - a 32 bit process is required.

in the Tests output window, and 

> File contains no data buffers
> File contains no data buffers
> Analysis failed

 in the Performance output window.

 If I set my unit test DLL's to be compiled to 32 bit, they no longer show in explorer. Is "Profile Test" not supported right now, or is there a configuration option I need to do?

**Comment by OsirisTerje** [comment]
What is your setting for "Test/Test Settings/Default Processor Architecture" ?

**Comment by Dispersia** [comment]
If I change it to x86, I receive

```
Exception System.InvalidOperationException, Exception thrown executing tests in myDLL.DLL
Operation is not valid due to the current state of the object.
```

even though it runs tests perfectly fine, I tried turning all projects to x86 on build, or anycpu, both resulting in above and the File contains no data buffers.

**Comment by OsirisTerje** [comment]
I have a confirmation on this,   it seems the profiling have stopped working.  A simple repro is here: https://github.com/OsirisTerje/ProfilingIssue , containing one mstest and one nunit rpoject with one test each.  The mstest works, the nunit doesn't, giving the same messages as   @Dispersia  reports above.

**Comment by duncanawoods** [comment]
I get the additional unwanted effect that trying to profile a test launches the startup executable too. I get the following errors warnings (running in x86):

	[24/08/2017 11:28:14 Informational] ------ Run test started ------
	[24/08/2017 11:28:15 Informational] NUnit Adapter 3.8.0.0: Test execution started
	[24/08/2017 11:28:15 Informational] Running selected tests in C:\Users\XXX\Documents\XXX\src\XXX\bin\Debug\netcoreapp2.0\XXX.dll
	[24/08/2017 11:28:15 Warning] Exception NUnit.Engine.NUnitEngineException, Exception thrown executing tests in C:\Users\XXX\Documents\XXX\src\XXX\bin\Debug\netcoreapp2.0\XXX.dll
	[24/08/2017 11:28:15 Warning] An exception occurred in the driver while loading tests.
	[24/08/2017 11:28:15 Informational] NUnit Adapter 3.8.0.0: Test execution complete
	[24/08/2017 11:28:15 Informational] ========== Run test finished: 0 run (0:00:00.6245767)

**Comment by OsirisTerje** [comment]
Just checked this again with VS 15.5.6 and NUnit3Testadapter 3.9, and now it does profile for me.  
@Dispersia  Can you check on your side?

**Comment by jons-aura** [comment]
@OsirisTerje I'm running into this issue as well. NUnit Adapter 3.9.0.0
Visual Studio 15.6.0 Preview 2.0

[2/19/2018 3:43:35 PM Informational] ** Instrumented C:\_source\Client\app\MMA.Business.Test\bin\Debug\netcoreapp2.0\MMA.Web.dll **
[2/19/2018 3:43:36 PM Informational] ** Instrumented C:\_source\Client\app\MMA.Business.Test\bin\Debug\netcoreapp2.0\MMA.Data.dll **
[2/19/2018 3:43:36 PM Informational] ** Instrumented C:\_source\Client\app\MMA.Business.Test\bin\Debug\netcoreapp2.0\MMA.Business.dll **
[2/19/2018 3:43:36 PM Informational] ** Instrumented C:\_source\Client\app\MMA.Business.Test\bin\Debug\netcoreapp2.0\MMA.Business.Test.dll **
[2/19/2018 3:43:36 PM Informational] ** Instrumented C:\_source\Client\app\MMA.Business.Test\bin\Debug\netcoreapp2.0\MMA.Interfaces.dll **
[2/19/2018 3:43:37 PM Informational] ------ Run test started ------
[2/19/2018 3:43:38 PM Informational] NUnit Adapter 3.9.0.0: Test execution started
[2/19/2018 3:43:38 PM Informational] Running selected tests in C:\_source\Client\app\MMA.Business.Test\bin\Debug\netcoreapp2.0\MMA.Business.Test.dll
[2/19/2018 3:43:38 PM Warning] Exception NUnit.Engine.NUnitEngineException, Exception thrown executing tests in C:\_source\Client\app\MMA.Business.Test\bin\Debug\netcoreapp2.0\MMA.Business.Test.dll
[2/19/2018 3:43:38 PM Warning] Cannot run tests in process - a 32 bit process is required.
[2/19/2018 3:43:38 PM Warning]    at NUnit.Engine.Runners.MasterTestRunner.InitializePackage()
   at NUnit.Engine.TestEngine.GetRunner(TestPackage package)
   at NUnit.VisualStudio.TestAdapter.NUnit3TestExecutor.RunAssembly(String assemblyPath, TestFilter filter) in C:\Users\Terje\Source\Repos\nunit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnit3TestExecutor.cs:line 213
[2/19/2018 3:43:38 PM Warning] Exception System.NullReferenceException, Exception thrown unloading tests from C:\_source\Client\app\MMA.Business.Test\bin\Debug\netcoreapp2.0\MMA.Business.Test.dll
[2/19/2018 3:43:38 PM Warning] Object reference not set to an instance of an object.
[2/19/2018 3:43:38 PM Warning]    at NUnit.VisualStudio.TestAdapter.NUnit3TestExecutor.RunAssembly(String assemblyPath, TestFilter filter) in C:\Users\Terje\Source\Repos\nunit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnit3TestExecutor.cs:line 311
[2/19/2018 3:43:38 PM Informational] NUnit Adapter 3.9.0.0: Test execution complete
[2/19/2018 3:43:38 PM Informational] ========== Run test finished: 0 run (0:00:01.467018) ==========

**Comment by jons-aura** [comment]
I just updated to Visual Studio 15.6.0 Preview 5.0 and now I get 
```
[2/19/2018 4:24:30 PM Informational] ------ Run test started ------
[2/19/2018 4:24:30 PM Informational] NUnit Adapter 3.9.0.0: Test execution started
[2/19/2018 4:24:30 PM Informational] Running selected tests in C:\_source\client\app\MMA.Business.Test\bin\Debug\netcoreapp2.0\MMA.Business.Test.dll
[2/19/2018 4:24:31 PM Warning] Exception System.InvalidOperationException, Exception thrown executing tests in C:\_source\client\app\MMA.Business.Test\bin\Debug\netcoreapp2.0\MMA.Business.Test.dll
[2/19/2018 4:24:31 PM Warning] Operation is not valid due to the current state of the object.
[2/19/2018 4:24:31 PM Warning]    at Mono.Cecil.ModuleDefinition.ReadSymbols(ISymbolReader reader)
   at Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters)
   at Mono.Cecil.ModuleReader.CreateModule(Image image, ReaderParameters parameters)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at NUnit.VisualStudio.TestAdapter.NavigationDataProvider.CacheNewTypes(String assemblyPath, IDictionary`2 types) in C:\Users\Terje\source\repos\nunit\nunit3-vs-adapter\src\NUnitTestAdapter\NavigationDataProvider.cs:line 85
   at NUnit.VisualStudio.TestAdapter.NavigationDataProvider.GetNavigationData(String className, String methodName) in C:\Users\Terje\source\repos\nunit\nunit3-vs-adapter\src\NUnitTestAdapter\NavigationDataProvider.cs:line 48
   at NUnit.VisualStudio.TestAdapter.TestConverter.MakeTestCaseFromXmlNode(XmlNode testNode) in C:\Users\Terje\source\repos\nunit\nunit3-vs-adapter\src\NUnitTestAdapter\TestConverter.cs:line 144
   at NUnit.VisualStudio.TestAdapter.TestConverter.ConvertTestCase(XmlNode testNode) in C:\Users\Terje\source\repos\nunit\nunit3-vs-adapter\src\NUnitTestAdapter\TestConverter.cs:line 79
   at NUnit.VisualStudio.TestAdapter.NUnit3TestExecutor.RunAssembly(String assemblyPath, TestFilter filter) in C:\Users\Terje\source\repos\nunit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnit3TestExecutor.cs:line 249
[2/19/2018 4:24:31 PM Informational] NUnit Adapter 3.9.0.0: Test execution complete
[2/19/2018 4:24:31 PM Informational] ========== Run test finished: 0 run (0:00:01.0830038) ==========
```

**Comment by jnm2** [comment]
@jons-aura The Mono.Cecil crash is fixed and soon to be merged and released. https://github.com/nunit/nunit3-vs-adapter/pull/454

**Comment by jnm2** [comment]
@Dispersia, @duncanawoods, @jons-aura: Is this still an issue in https://www.nuget.org/packages/NUnit3TestAdapter/3.10.0?

**Comment by jons-aura** [comment]
I now get:

```
[3/13/2018 9:21:44 AM Informational] ------ Run test started ------
[3/13/2018 9:21:44 AM Informational] NUnit Adapter 3.9.0.0: Test execution started
[3/13/2018 9:21:44 AM Informational] Running all tests in C:\_source\Client\app\MMA.Business.Test\bin\Release\netcoreapp2.0\MMA.Business.Test.dll
[3/13/2018 9:21:44 AM Warning] Assembly not supported: C:\_source\Client\app\MMA.Business.Test\bin\Release\netcoreapp2.0\MMA.Business.Test.dll
[3/13/2018 9:21:44 AM Informational] NUnit Adapter 3.9.0.0: Test execution complete
[3/13/2018 9:21:44 AM Warning] No test is available in C:\_source\Client\app\MMA.Business.Test\bin\Release\netcoreapp2.0\MMA.Business.Test.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
[3/13/2018 9:21:45 AM Informational] ========== Run test finished: 0 run (0:00:00.7679751) ==========
```

**Comment by jons-aura** [comment]
NUnit seems to be working now, but I still can't view results. For some reason I get "File contains no data buffers". I also ran into that trying to profile a dedicated console app and created an item on the Visual Studio Developer Community a while ago https://developercommunity.visualstudio.com/content/problem/200435/instrumenting-net-core-20-console-app-file-contain.html


```
[3/13/2018 9:29:55 AM Informational] ------ Load Playlist started ------
[3/13/2018 9:29:55 AM Informational] ========== Load Playlist finished (0:00:00.0049993) ==========
[3/13/2018 9:30:15 AM Informational] ** Instrumented C:\_source\Client\app\MMA.Business.Test\bin\Release\netcoreapp2.0\MMA.Web.dll **
[3/13/2018 9:30:15 AM Informational] ** Instrumented C:\_source\Client\app\MMA.Business.Test\bin\Release\netcoreapp2.0\MMA.Data.dll **
[3/13/2018 9:30:15 AM Informational] ** Instrumented C:\_source\Client\app\MMA.Business.Test\bin\Release\netcoreapp2.0\MMA.Business.dll **
[3/13/2018 9:30:16 AM Informational] ** Instrumented C:\_source\Client\app\MMA.Business.Test\bin\Release\netcoreapp2.0\MMA.Business.Test.dll **
[3/13/2018 9:30:16 AM Informational] ** Instrumented C:\_source\Client\app\MMA.Business.Test\bin\Release\netcoreapp2.0\MMA.Interfaces.dll **
[3/13/2018 9:30:16 AM Informational] ** Instrumented C:\_source\Client\app\MMA.Business.Test\bin\Release\netcoreapp2.0\APPDataDumper.dll **
[3/13/2018 9:30:17 AM Informational] ------ Run test started ------
[3/13/2018 9:30:18 AM Informational] NUnit Adapter 3.10.0.21: Test execution started
[3/13/2018 9:30:18 AM Informational] Running all tests in C:\_source\Client\app\MMA.Business.Test\bin\Release\netcoreapp2.0\MMA.Business.Test.dll
[3/13/2018 9:30:18 AM Warning] Assembly not supported: C:\_source\Client\app\MMA.Business.Test\bin\Release\netcoreapp2.0\MMA.Business.Test.dll
[3/13/2018 9:30:18 AM Informational] NUnit Adapter 3.10.0.21: Test execution complete
[3/13/2018 9:30:18 AM Warning] No test is available in C:\_source\Client\app\MMA.Business.Test\bin\Release\netcoreapp2.0\MMA.Business.Test.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
[3/13/2018 9:30:18 AM Informational] ========== Run test finished: 0 run (0:00:01.5810206) ==========
```

**Comment by jnm2** [comment]
@jons-aura It looks like after the assembly is instrumented, NUnit can't load it. What are you using to profile the assemblies, Live Unit Testing? A small repro would speed this up.

**Comment by CrustyJew** [comment]
@jnm2 I'm able to reproduce it with the following set up:

Visual Studio 2017 v15.6.6
NUnit 3 Test Adapter v3.10.0.0


1. Install latest NUnit Project Template `dotnet new -i NUnit3.DotNetNew.Template`
2. Create folder and create NUnit project `dotnet new nunit`
3. Open project in VS2017
4. Build project
5. Go to Test Explorer, right click, and "Profile Test"

Output:

> [4/13/2018 3:16:27 PM Informational] ------ Load Playlist started ------
> [4/13/2018 3:16:27 PM Informational] ========== Load Playlist finished (0:00:00.0150099) ==========
> [4/13/2018 3:17:32 PM Informational] ------ Load Playlist started ------
> [4/13/2018 3:17:32 PM Informational] ========== Load Playlist finished (0:00:00.015624) ==========
> [4/13/2018 3:17:45 PM Informational] ------ Discover test started ------
> [4/13/2018 3:17:47 PM Informational] NUnit Adapter 3.10.0.21: Test discovery starting
> [4/13/2018 3:17:47 PM Informational] NUnit Adapter 3.10.0.21: Test discovery complete
> [4/13/2018 3:17:48 PM Informational] ========== Discover test finished: 1 found (0:00:02.2796415) ==========
> [4/13/2018 3:18:10 PM Informational] ** Instrumented C:\Temp\testtemp\bin\Debug\netcoreapp2.0\testtemp.dll **
> [4/13/2018 3:18:11 PM Informational] ------ Run test started ------
> [4/13/2018 3:18:12 PM Informational] NUnit Adapter 3.10.0.21: Test execution started
> [4/13/2018 3:18:14 PM Informational] Running selected tests in C:\Temp\testtemp\bin\Debug\netcoreapp2.0\testtemp.dll
> [4/13/2018 3:18:14 PM Warning] Assembly not supported: C:\Temp\testtemp\bin\Debug\netcoreapp2.0\testtemp.dll
> [4/13/2018 3:18:14 PM Informational] NUnit Adapter 3.10.0.21: Test execution complete
> [4/13/2018 3:18:14 PM Informational] ========== Run test finished: 0 run (0:00:03.0462087) ==========

Changing project to x86 from AnyCpu has consistently frozen Visual Studio when attempting to profile it. 

I'm still experimenting but will update if I find anything else.

**Comment by CrustyJew** [comment]
Changing the default test Processor Architecture to x64 and changing the test project's CPU type from AnyCpu to x64 allowed me to profile the test successfully.

**Comment by CrustyJew** [comment]
@jnm2 looks like AnyCPU and 64-bit test architecture works as well, but still doesn't resolve function names. Just shows everything as memory references `0x06000009` etc.

It is just a single test that has `Assert.Pass();` in it.

**Comment by jnm2** [comment]
What happens if you keep the same scenario and replace NUnit with MSTest or xUnit?

**Comment by crystalgreen** [comment]
The error may be misleading. I had the same issue `File contains no data buffers` using NUnit 3.10.1, NUnit3TestAdapter 3.10.0.
But I got it to work. I was referencing signed assemblies, the test project was unsigned. When I [disabled assembly signing](https://stackoverflow.com/questions/2711484/how-can-i-profile-signed-assemblies-with-vs-2010-or-vs-2013) before running the test, the error vanished. I guess that resigning would be the more secure alternative.

**Comment by Dispersia** [comment]
If someone else still has this issue, we can re open, however it works for me now so I am going to close it.
