### ISSUE TITLE
.NET Core 3.1 KeyNotFoundException, Unable to find UniqueTest VSTestAdapter

### ISSUE THREAD

**Issue by jsgoupil** [nunit/nunit3-vs-adapter#685]
```
========== Discovery finished: 120 tests found (0:00:01.4609728) ==========
System.Collections.Generic.KeyNotFoundException: Unable to find UniqueTest VSTestAdapter,D:\path_to_file\bin\Debug\netcoreapp3.1\MyFile.Tests.dll,MyFile.Tests.Services.ClassNameTests.ExtractUnitNumber_Success,:0a4559b4-6ae5-7f70-0224-19d70ce93653
   at Microsoft.VisualStudio.TestStorage.TestStoreHierarchyNode.LookupUniqueTest(MergedTestIndex index)
   at Microsoft.VisualStudio.TestStorage.TestStoreHierarchyIndex.<>c__DisplayClass41_0.<GetTestContainersForNodes>b__0(TestStoreHierarchyNode ct)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Microsoft.VisualStudio.TestStorage.TestStore.UpdateContainerConfigs(IDictionary`2 allContainerConfigs, IEnumerable`1 containers, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestStorage.TestStore.GetTestContainersForNodes(Int32 viewId, IEnumerable`1 nodeIds, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestWindow.Host.TestWindowStoreService.<>c__DisplayClass34_0.<GetTestSourcesAsync>b__0()
   at Microsoft.VisualStudio.TestWindow.Extensibility.ILoggerExtensions.<CallWithCatchAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.TestWindow.Controller.TestContainerConfigurationQueryByTestsBase.<QueryTestContainerConfigurationsAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestWindow.Controller.TestContainerConfigurationQuery.<GetTestContainerConfigurationsAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestWindow.Controller.TestRunConfiguration.<UpdateAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestWindow.Controller.RunOperation.<RunTestsAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestWindow.Controller.Operation.<<Execute>b__37_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestWindow.Extensibility.ILoggerExtensions.<CallWithCatchAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

* NUnit: 3.12.0
* NUnit3TestAdapter: 3.16.0
* Framework: netcoreapp3.1

I was on .NET Core 2.2 before and it worked fine. Is there anything preventing 3.1 from running these tests in VS2019 ?

**Comment by OsirisTerje** [comment]
Works on my machine :-)  So, no, it should work.

Does it work if you just test a blank new .net core 3 test project ?

Can you upload a small repro ?

**Comment by jsgoupil** [comment]
Although I really want to give you a repro or access to my repository, but this is not as simple as it seems. Small repro does not show this behavior. Restarting Visual Studio usually works, but after playing around with the code and the tests, I end up in an unusable state. Tests becomes "untested" (even though I didn't change them), then I start getting all sort of errors.

Now, I am not super knowledgeable how you handle your tests under the hood, but I don't see any NUnit callstack here... so it could be a Microsoft issue, or it could be that you send bad data to the VS Test?

```
[1/5/2020 2:53:23.946 PM] ========== Run finished: 6 tests run (0:00:02.1462573) ==========
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Microsoft.VisualStudio.TestWindow.Client.VirtualTestNodeHierarchy.<>c__DisplayClass42_1.<<RefreshTestsAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestWindow.Utilities.EventPumpExtensions.<>c__DisplayClass3_0.<<EnqueueAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestWindow.Extensibility.ILoggerExtensions.<CallWithCatchAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Microsoft.VisualStudio.TestWindow.Client.VirtualTestNodeHierarchy.<>c__DisplayClass42_1.<<RefreshTestsAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestWindow.Utilities.EventPumpExtensions.<>c__DisplayClass3_0.<<EnqueueAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestWindow.Extensibility.ILoggerExtensions.<CallWithCatchAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Microsoft.VisualStudio.TestWindow.Client.VirtualTestNodeHierarchy.<>c__DisplayClass42_1.<<RefreshTestsAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestWindow.Utilities.EventPumpExtensions.<>c__DisplayClass3_0.<<EnqueueAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestWindow.Extensibility.ILoggerExtensions.<CallWithCatchAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Microsoft.VisualStudio.TestWindow.Client.VirtualTestNodeHierarchy.<>c__DisplayClass42_1.<<RefreshTestsAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestWindow.Utilities.EventPumpExtensions.<>c__DisplayClass3_0.<<EnqueueAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestWindow.Extensibility.ILoggerExtensions.<CallWithCatchAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Microsoft.VisualStudio.TestWindow.Client.VirtualTestNodeHierarchy.<>c__DisplayClass42_1.<<RefreshTestsAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestWindow.Utilities.EventPumpExtensions.<>c__DisplayClass3_0.<<EnqueueAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestWindow.Extensibility.ILoggerExtensions.<CallWithCatchAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by jsgoupil** [comment]
I'm using some `[TestCase]` if that could help narrow down the issue...

**Comment by jsgoupil** [comment]
Also, I just decided to do a little git clean -xfd, and it seems to work better. So I will keep using my code for a couple more hours and report here if that helped.
That could mean some remnant of .NET core 2.2 stuff stayed while .NET Core 3.1 has been updated.

**Comment by OsirisTerje** [comment]
There are a series of bugs related to the "An item with the same key has already been added " exception you see.  You can see them using this query: https://github.com/nunit/nunit3-vs-adapter/issues?utf8=%E2%9C%93&q=is%3Aissue+An+item+with+the+same+key+has+already+been+added+ 
Note that most have been fixed by the 3.16 version of the adapter.  But check the issues and see if any of them apply to you. 

MS PG has also confirmed they have an internal bug related to some of the same issues, and a fix is coming.  I'll ping them again about the state of this, and a possible ETA.
Also ensure you have the latest version of VS,  16.4

**Comment by jsgoupil** [comment]
Thanks, I have all of the latest here. And I am also on 3.16. All of this started when I migrated from 2.2 to 3.1, but I didn't clean all my folders.
Probably a non-scenario. The other bugs you pointed out look really similar to the problems I have.
I can close this bug when everything work.

**Comment by OsirisTerje** [comment]
I revisited the repro for 676 now, and I can repro the same issue there, with 16.4 and 3.16.  I'll ping the PG about it.

**Comment by OsirisTerje** [comment]
The exception is fixed in the upcoming 16.5 Preview -2, which should be out real soon now :-)

**Comment by jsgoupil** [comment]
I have been hitting this bug constantly now... I updated to 16.5.0-preview-20200102-01
There was an Unknown Project lingering at the top. I have to clear my .vs folder.

Now it "works", but when saving, I get a lot of random tests that become "not run test".
Now I get back to my:

```
[1/6/2020 4:19:41.936 PM] ========== Discovery finished: 148 tests found (0:00:01.5175838) ==========
System.Collections.Generic.KeyNotFoundException: Unable to find UniqueTest VSTestAdapter,
```

which does not run tests actually.

**Comment by OsirisTerje** [comment]
I don't think Preview 2 is out right now, from this page https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview I only see preview 1.

**Comment by jsgoupil** [comment]
Still not working to me with the Preview 2 `16.5.0-preview-20200110-02`

```
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
```

**Comment by IvanStoychev** [comment]
I also am experiencing the same issue.
If it will help I can point you to my repo in which I am experiencing the issue - https://github.com/IvanStoychev/Useful.String.Extensions

I also believe, in my case, it happens because I use "MemberData" and an "IEnumerable" property, as you can see in the "RemoverTests" class.

**Comment by OsirisTerje** [comment]
@IvanStoychev Is this with Preview 2 ?
@jsgoupil It looks like you have Preview 1, not Preview 2.  Preview 2 was released Jan 22,  Can you confirm ?

**Comment by IvanStoychev** [comment]
@OsirisTerje , sorry no.

**Comment by OsirisTerje** [comment]
@IvanStoychev I tried to use your repo for confirming, but it doesn't compile. It refers to some local folders you have, I think.

**Comment by OsirisTerje** [comment]
Solved with Visual Studio 2019, version 16.5 Preview 2

**Comment by IvanStoychev** [comment]
@OsirisTerje , ah, sorry, now I realize the package information, relating to my local folders, is in the .csproj file.

Indeed I have xUnit but the error I got was the exact same and I couldn't find anything on the 'Net about it, so I thought to post here. :)

**Comment by jsgoupil** [comment]
The bug does not seem to happen anymore, but changing a [TestCase] of one function marks a panoply of tests as "not run tests"
Not pleasant, but I can run tests at least now.
I'm on v16.5.0-preview-20200116-01

**Comment by gaurav-dogra** [comment]
I and other colleagues facing this issue in VS 17.5, we are using nUnit

**Comment by kristol07** [comment]
> I and other colleagues facing this issue in VS 17.5, we are facing this issue with specFlow

same issue here (VS Professional 2022, v17.5.1)

**Comment by AidanMcD** [comment]
same issue here (VS Professional 2022, v17.5.1) & specflow

**Comment by OsirisTerje** [comment]
@gaurav-dogra @kristol07 @AidanMcD  We need something more to go on here.  Can you provide a repro for this ?  

And, are you sure you have a

**Comment by 928PJY** [comment]
Same issue here (VS Enterprise 2022 17.5.1) with dotnet/yunit package.

**Comment by OsirisTerje** [comment]
@928PJY No repro.

**Comment by Muhammad-Ali-Qadri** [comment]
Same issue here (VS Professional 2022 17.5.1) and Specflow.

**Comment by OsirisTerje** [comment]
@Muhammad-Ali-Qadri And still no repro?

**Comment by kristol07** [comment]
> @Muhammad-Ali-Qadri And still no repro?

@OsirisTerje hi Osiris, sorry for late reply. I can try to craft a mini repo and see whether it can be reproduced. 

BTW, I see many recent replies replated to specflow and vs 17.5, it may not be the issue of nunit but of the previous two... people came here because they searched the same error message in Google and found the link to this discussion, that's actually my case, my project doesn't use nunit at all. Really sorry for that if made any trouble to you. 

Let me try first, and I will reply here later.

**Comment by kristol07** [comment]
@OsirisTerje  new small project created with template just doesn't reproduce this issue. I was using MSTest framework, tired to update it to latest version without breaking change, the problem remains. You can ignore my case however, since it's not related to NUnit.

**Comment by OsirisTerje** [comment]
@gaurav-dogra @kristol07 @AidanMcD @Muhammad-Ali-Qadri  Can you guys raise an issue on Microsoft Developer Community, link here, and I can help pointing people to it.

**Comment by Santhis** [comment]
I am facing the same issue VS Community  2022  17.5.2 with SpecFlow

**Comment by OsirisTerje** [comment]
@Santhis You need to raise this issue with SpecFlow.
